import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import NotistackProvider from "./components/notistackProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "O Complex Test Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NotistackProvider>
        <body className={`${inter.variable} antialiased`}>
          <Header />
          {children}
        </body>
      </NotistackProvider>
    </html>
  );
}
